[package]
name = "euphorium"
version = "0.6.0"
edition = "2024"
description = "Painless audio playback for native and web platforms"
documentation = "https://docs.rs/euphorium"
readme = "README.md"
repository = "https://github.com/egakareta/euphorium"
license = "MIT OR Apache-2.0"
keywords = ["audio", "playback", "rodio", "wasm", "waveform"]
categories = ["multimedia::audio", "wasm"]
include = [
    "/CHANGELOG.md",
    "/LICENSE-APACHE",
    "/LICENSE-MIT",
    "/README.md",
    "/src/**",
]

[lib]
name = "euphorium"
path = "src/lib.rs"

[[bin]]
name = "euphorium"
path = "src/cli.rs"
required-features = ["cli"]

[[bench]]
harness = false
name = "controls"

[dependencies]
clap = { version = "4.5", features = ["derive"], optional = true }
cpal = "0.18"
dasp_sample = "0.11"
log = "0.4"
parking_lot_core = { version = "0.9", optional = true }
rodio = { package = "euphorium-rodio", path = "rodio", version = "0.22.2-euph.1", default-features = false, features = [
    "playback",
    "wasm-bindgen",
] }
thiserror = "2"
web-time = "1"

[dev-dependencies]
fastrand = { version = "2", features = ["js"] }
include_dir = "0.7"

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
criterion = "0.8"
pollster = "1"

[target.'cfg(target_arch = "wasm32")'.dependencies]
cpal = { version = "0.18", features = ["wasm-bindgen"] }
getrandom = { version = "0.4", features = ["wasm_js"] }
js-sys = "0.3"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
wasm_sync = "0.1"
web-sys = { version = "0.3", features = [
    "AudioContext",
    "AudioContextState",
    "Response",
    "Window",
    "console",
] }

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test = "0.3"
web-sys = { version = "0.3", features = ["Blob", "Url"] }

[features]
default = ["cli", "mp3", "vorbis", "wav"]
asio = ["cpal/asio"]
cli = ["dep:clap"]
flac = ["rodio/flac"]
jack = ["cpal/jack"]
mp3 = ["rodio/mp3"]
mp4 = ["rodio/mp4"]
nightly = ["cpal/audioworklet", "parking_lot_core/nightly"]
vorbis = ["rodio/vorbis"]
wav = ["rodio/wav"]
